### ISSUE TITLE
Fuature request: support DNS

### ISSUE THREAD

**Issue by p0i5k** [benyamin218118/tcpforwarder#2]
For example:
Server's IP is 1.2.3.4. Also, server has two DNS one.test.org and two.test.org
Run two process:
```
tcpforwarder -lHost one.test.org -lPort 123 -rHost 10.0.0.1 -rPort 123
tcpforwarder -lHost two.test.org -lPort 123 -rHost 10.0.0.2 -rPort 123
```
Expected behavior:
First process forwarding port 123 to 10.0.0.1
Second process forwarding port 123 to 10.0.0.2

Current behavior:
Cannot run second process: panic: address already in use

**Comment by benyamin218118** [comment]
hi, tnx for using tcpforwarder!

the reason you faced this error `address already in use` is you are trying to listen on port `123` twice which is not possible because you can't listen on the same tcp port more than once.

and you are using it in a wrong way btw, `lHost` is the listen host and `rHost` is remote or target Host. you can leave the LHost and just set the rHost to one.test.org or two.test.org. check the docs

and im not adding DNS support as this is a `tcp` forwarder and dns works with udp.
but you can try `tunnel` for udp
take a look(https://github.com/benyamin218118/tunnel)
